// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: misestm/rest_query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type RestQueryDidRequest struct {
	MisesId string `protobuf:"bytes,1,opt,name=mises_id,json=misesId,proto3" json:"mises_id,omitempty"`
}

func (m *RestQueryDidRequest) Reset()         { *m = RestQueryDidRequest{} }
func (m *RestQueryDidRequest) String() string { return proto.CompactTextString(m) }
func (*RestQueryDidRequest) ProtoMessage()    {}
func (*RestQueryDidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d6cefbd419a531, []int{0}
}
func (m *RestQueryDidRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RestQueryDidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RestQueryDidRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RestQueryDidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestQueryDidRequest.Merge(m, src)
}
func (m *RestQueryDidRequest) XXX_Size() int {
	return m.Size()
}
func (m *RestQueryDidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestQueryDidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestQueryDidRequest proto.InternalMessageInfo

func (m *RestQueryDidRequest) GetMisesId() string {
	if m != nil {
		return m.MisesId
	}
	return ""
}

type RestQueryDidResponse struct {
	DidRegistry *DidRegistry `protobuf:"bytes,1,opt,name=didRegistry,proto3" json:"didRegistry,omitempty"`
}

func (m *RestQueryDidResponse) Reset()         { *m = RestQueryDidResponse{} }
func (m *RestQueryDidResponse) String() string { return proto.CompactTextString(m) }
func (*RestQueryDidResponse) ProtoMessage()    {}
func (*RestQueryDidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d6cefbd419a531, []int{1}
}
func (m *RestQueryDidResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RestQueryDidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RestQueryDidResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RestQueryDidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestQueryDidResponse.Merge(m, src)
}
func (m *RestQueryDidResponse) XXX_Size() int {
	return m.Size()
}
func (m *RestQueryDidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RestQueryDidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RestQueryDidResponse proto.InternalMessageInfo

func (m *RestQueryDidResponse) GetDidRegistry() *DidRegistry {
	if m != nil {
		return m.DidRegistry
	}
	return nil
}

type RestQueryUserRequest struct {
	MisesId string `protobuf:"bytes,1,opt,name=mises_id,json=misesId,proto3" json:"mises_id,omitempty"`
}

func (m *RestQueryUserRequest) Reset()         { *m = RestQueryUserRequest{} }
func (m *RestQueryUserRequest) String() string { return proto.CompactTextString(m) }
func (*RestQueryUserRequest) ProtoMessage()    {}
func (*RestQueryUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d6cefbd419a531, []int{2}
}
func (m *RestQueryUserRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RestQueryUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RestQueryUserRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RestQueryUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestQueryUserRequest.Merge(m, src)
}
func (m *RestQueryUserRequest) XXX_Size() int {
	return m.Size()
}
func (m *RestQueryUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestQueryUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestQueryUserRequest proto.InternalMessageInfo

func (m *RestQueryUserRequest) GetMisesId() string {
	if m != nil {
		return m.MisesId
	}
	return ""
}

type RestQueryUserResponse struct {
	UserInfo *UserInfo `protobuf:"bytes,1,opt,name=userInfo,proto3" json:"userInfo,omitempty"`
}

func (m *RestQueryUserResponse) Reset()         { *m = RestQueryUserResponse{} }
func (m *RestQueryUserResponse) String() string { return proto.CompactTextString(m) }
func (*RestQueryUserResponse) ProtoMessage()    {}
func (*RestQueryUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d6cefbd419a531, []int{3}
}
func (m *RestQueryUserResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RestQueryUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RestQueryUserResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RestQueryUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestQueryUserResponse.Merge(m, src)
}
func (m *RestQueryUserResponse) XXX_Size() int {
	return m.Size()
}
func (m *RestQueryUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RestQueryUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RestQueryUserResponse proto.InternalMessageInfo

func (m *RestQueryUserResponse) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

type RestQueryUserRelationRequest struct {
	MisesId    string             `protobuf:"bytes,1,opt,name=mises_id,json=misesId,proto3" json:"mises_id,omitempty"`
	Filter     string             `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *RestQueryUserRelationRequest) Reset()         { *m = RestQueryUserRelationRequest{} }
func (m *RestQueryUserRelationRequest) String() string { return proto.CompactTextString(m) }
func (*RestQueryUserRelationRequest) ProtoMessage()    {}
func (*RestQueryUserRelationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d6cefbd419a531, []int{4}
}
func (m *RestQueryUserRelationRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RestQueryUserRelationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RestQueryUserRelationRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RestQueryUserRelationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestQueryUserRelationRequest.Merge(m, src)
}
func (m *RestQueryUserRelationRequest) XXX_Size() int {
	return m.Size()
}
func (m *RestQueryUserRelationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestQueryUserRelationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestQueryUserRelationRequest proto.InternalMessageInfo

func (m *RestQueryUserRelationRequest) GetMisesId() string {
	if m != nil {
		return m.MisesId
	}
	return ""
}

func (m *RestQueryUserRelationRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *RestQueryUserRelationRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type RestQueryUserRelationResponse struct {
	UserRelation []*UserRelation     `protobuf:"bytes,1,rep,name=userRelation,proto3" json:"userRelation,omitempty"`
	Pagination   *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *RestQueryUserRelationResponse) Reset()         { *m = RestQueryUserRelationResponse{} }
func (m *RestQueryUserRelationResponse) String() string { return proto.CompactTextString(m) }
func (*RestQueryUserRelationResponse) ProtoMessage()    {}
func (*RestQueryUserRelationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d6cefbd419a531, []int{5}
}
func (m *RestQueryUserRelationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RestQueryUserRelationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RestQueryUserRelationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RestQueryUserRelationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestQueryUserRelationResponse.Merge(m, src)
}
func (m *RestQueryUserRelationResponse) XXX_Size() int {
	return m.Size()
}
func (m *RestQueryUserRelationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RestQueryUserRelationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RestQueryUserRelationResponse proto.InternalMessageInfo

func (m *RestQueryUserRelationResponse) GetUserRelation() []*UserRelation {
	if m != nil {
		return m.UserRelation
	}
	return nil
}

func (m *RestQueryUserRelationResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*RestQueryDidRequest)(nil), "misesid.misestm.misestm.RestQueryDidRequest")
	proto.RegisterType((*RestQueryDidResponse)(nil), "misesid.misestm.misestm.RestQueryDidResponse")
	proto.RegisterType((*RestQueryUserRequest)(nil), "misesid.misestm.misestm.RestQueryUserRequest")
	proto.RegisterType((*RestQueryUserResponse)(nil), "misesid.misestm.misestm.RestQueryUserResponse")
	proto.RegisterType((*RestQueryUserRelationRequest)(nil), "misesid.misestm.misestm.RestQueryUserRelationRequest")
	proto.RegisterType((*RestQueryUserRelationResponse)(nil), "misesid.misestm.misestm.RestQueryUserRelationResponse")
}

func init() { proto.RegisterFile("misestm/rest_query.proto", fileDescriptor_56d6cefbd419a531) }

var fileDescriptor_56d6cefbd419a531 = []byte{
	// 530 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0xe7, 0x56, 0x1a, 0xed, 0xdb, 0x71, 0xc0, 0x1b, 0x25, 0x8b, 0x4a, 0x34, 0x22, 0xfe,
	0x4c, 0x68, 0xb3, 0x69, 0x11, 0xdc, 0xb8, 0x20, 0x54, 0xd4, 0x1b, 0x44, 0x82, 0x03, 0x07, 0xa6,
	0x74, 0xf1, 0x82, 0xa5, 0x26, 0xce, 0x62, 0x07, 0x31, 0x71, 0x40, 0xe2, 0x13, 0x20, 0x71, 0xe2,
	0xc6, 0x07, 0xe0, 0xc6, 0x97, 0xe0, 0x38, 0x89, 0x0b, 0x47, 0xd4, 0xf2, 0x41, 0x50, 0x1d, 0xa7,
	0x73, 0x07, 0xa5, 0xe5, 0xd4, 0xda, 0x7e, 0x9f, 0xe7, 0xfd, 0xe5, 0xf5, 0x23, 0x83, 0x93, 0x70,
	0xc9, 0xa4, 0x4a, 0x68, 0xce, 0xa4, 0x3a, 0x38, 0x2e, 0x58, 0x7e, 0x42, 0xb2, 0x5c, 0x28, 0x81,
	0xaf, 0xe8, 0x13, 0x1e, 0x11, 0x53, 0x51, 0xfd, 0xba, 0x9d, 0x58, 0x88, 0x78, 0xc4, 0x68, 0x98,
	0x71, 0x1a, 0xa6, 0xa9, 0x50, 0xa1, 0xe2, 0x22, 0x95, 0xa5, 0xcc, 0xbd, 0x7d, 0x28, 0x64, 0x22,
	0x24, 0x1d, 0x86, 0x92, 0x51, 0xed, 0x47, 0x5f, 0x77, 0x87, 0x4c, 0x85, 0x5d, 0x9a, 0x85, 0x31,
	0x4f, 0x75, 0xb1, 0xa9, 0xdd, 0xae, 0x9a, 0x3f, 0xe2, 0x51, 0xc0, 0x62, 0x2e, 0x55, 0xd5, 0xdd,
	0x6d, 0x57, 0x47, 0xcf, 0x24, 0xcb, 0x07, 0xe9, 0x91, 0x30, 0xfb, 0xae, 0xbd, 0x1f, 0xb0, 0x91,
	0x65, 0xe7, 0xdf, 0x81, 0xcd, 0x80, 0x49, 0xf5, 0x74, 0xda, 0x54, 0x3b, 0x1e, 0x17, 0x4c, 0x2a,
	0xbc, 0x0d, 0x0d, 0x2d, 0x3a, 0xe0, 0x91, 0x83, 0x76, 0xd0, 0x6e, 0x33, 0xb8, 0xa0, 0xd7, 0x83,
	0xc8, 0x7f, 0x09, 0x5b, 0xf3, 0x0a, 0x99, 0x89, 0x54, 0x32, 0xdc, 0x87, 0x56, 0x74, 0x86, 0xa4,
	0x55, 0xad, 0xde, 0x75, 0xb2, 0x60, 0x22, 0xc4, 0xc2, 0x0f, 0x6c, 0xa1, 0xdf, 0xb5, 0xfc, 0x4b,
	0xe0, 0xa5, 0x48, 0xcf, 0xe1, 0xf2, 0x39, 0x89, 0x61, 0x7a, 0x00, 0x8d, 0xc2, 0xcc, 0xc2, 0x00,
	0x5d, 0x5b, 0x08, 0x54, 0x0d, 0x2d, 0x98, 0x49, 0xfc, 0x4f, 0x08, 0x3a, 0xe7, 0x8c, 0xcb, 0xe1,
	0x2d, 0x67, 0xc2, 0x6d, 0x58, 0x3f, 0xe2, 0x23, 0xc5, 0x72, 0xa7, 0xa6, 0x0f, 0xcc, 0x0a, 0xf7,
	0x01, 0xce, 0xee, 0xd4, 0xa9, 0x6b, 0xa8, 0x9b, 0xa4, 0x0c, 0x00, 0x99, 0x06, 0x80, 0x94, 0x81,
	0x32, 0x01, 0x20, 0x4f, 0xc2, 0x98, 0x99, 0x76, 0x81, 0xa5, 0xf4, 0xbf, 0x22, 0xb8, 0xba, 0x80,
	0xcd, 0x7c, 0xfc, 0x00, 0x36, 0x0a, 0x6b, 0xdf, 0x41, 0x3b, 0xf5, 0xdd, 0x56, 0xef, 0xc6, 0x3f,
	0x07, 0x30, 0x33, 0x99, 0x93, 0xe2, 0xc7, 0x73, 0xd0, 0x35, 0x0d, 0x7d, 0x6b, 0x29, 0x74, 0xc9,
	0x61, 0x53, 0xf7, 0xbe, 0xd4, 0xa1, 0x39, 0xa3, 0xc6, 0x6f, 0xa1, 0x51, 0xc5, 0x08, 0xef, 0x2d,
	0xe4, 0xfa, 0x4b, 0x3e, 0xdd, 0xfd, 0x15, 0xab, 0x4b, 0x04, 0x1f, 0xbf, 0xff, 0xfe, 0xeb, 0x63,
	0x6d, 0x03, 0x03, 0xd5, 0x65, 0x34, 0xe2, 0x11, 0x7e, 0x07, 0xcd, 0xd9, 0xec, 0xf0, 0x0a, 0x7e,
	0x56, 0x16, 0x5d, 0xb2, 0x6a, 0xb9, 0xe9, 0xbf, 0xa9, 0xfb, 0x5f, 0xc4, 0x2d, 0xd3, 0x7f, 0x3a,
	0x5c, 0xfc, 0x19, 0xc1, 0xa5, 0x3f, 0x6e, 0x0f, 0xdf, 0x5b, 0xd5, 0x7a, 0x2e, 0x89, 0xee, 0xfd,
	0xff, 0x95, 0x19, 0xb2, 0x8e, 0x26, 0x6b, 0xe3, 0x2d, 0x8b, 0x8c, 0xe6, 0xa6, 0xea, 0x61, 0xff,
	0xdb, 0xd8, 0x43, 0xa7, 0x63, 0x0f, 0xfd, 0x1c, 0x7b, 0xe8, 0xc3, 0xc4, 0x5b, 0x3b, 0x9d, 0x78,
	0x6b, 0x3f, 0x26, 0xde, 0xda, 0x8b, 0xbd, 0x98, 0xab, 0x57, 0xc5, 0x90, 0x1c, 0x8a, 0xa4, 0x54,
	0xee, 0xf3, 0xc8, 0xfc, 0x51, 0x09, 0x7d, 0x43, 0xab, 0x27, 0x47, 0x9d, 0x64, 0x4c, 0x0e, 0xd7,
	0xf5, 0x63, 0x73, 0xf7, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x75, 0x80, 0xe4, 0x3a, 0x05,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RestQueryClient is the client API for RestQuery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RestQueryClient interface {
	// query a did
	QueryDid(ctx context.Context, in *RestQueryDidRequest, opts ...grpc.CallOption) (*RestQueryDidResponse, error)
	// query a user info
	QueryUser(ctx context.Context, in *RestQueryUserRequest, opts ...grpc.CallOption) (*RestQueryUserResponse, error)
	// query user relations
	QueryUserRelation(ctx context.Context, in *RestQueryUserRelationRequest, opts ...grpc.CallOption) (*RestQueryUserRelationResponse, error)
}

type restQueryClient struct {
	cc grpc1.ClientConn
}

func NewRestQueryClient(cc grpc1.ClientConn) RestQueryClient {
	return &restQueryClient{cc}
}

func (c *restQueryClient) QueryDid(ctx context.Context, in *RestQueryDidRequest, opts ...grpc.CallOption) (*RestQueryDidResponse, error) {
	out := new(RestQueryDidResponse)
	err := c.cc.Invoke(ctx, "/misesid.misestm.misestm.RestQuery/QueryDid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restQueryClient) QueryUser(ctx context.Context, in *RestQueryUserRequest, opts ...grpc.CallOption) (*RestQueryUserResponse, error) {
	out := new(RestQueryUserResponse)
	err := c.cc.Invoke(ctx, "/misesid.misestm.misestm.RestQuery/QueryUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restQueryClient) QueryUserRelation(ctx context.Context, in *RestQueryUserRelationRequest, opts ...grpc.CallOption) (*RestQueryUserRelationResponse, error) {
	out := new(RestQueryUserRelationResponse)
	err := c.cc.Invoke(ctx, "/misesid.misestm.misestm.RestQuery/QueryUserRelation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RestQueryServer is the server API for RestQuery service.
type RestQueryServer interface {
	// query a did
	QueryDid(context.Context, *RestQueryDidRequest) (*RestQueryDidResponse, error)
	// query a user info
	QueryUser(context.Context, *RestQueryUserRequest) (*RestQueryUserResponse, error)
	// query user relations
	QueryUserRelation(context.Context, *RestQueryUserRelationRequest) (*RestQueryUserRelationResponse, error)
}

// UnimplementedRestQueryServer can be embedded to have forward compatible implementations.
type UnimplementedRestQueryServer struct {
}

func (*UnimplementedRestQueryServer) QueryDid(ctx context.Context, req *RestQueryDidRequest) (*RestQueryDidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryDid not implemented")
}
func (*UnimplementedRestQueryServer) QueryUser(ctx context.Context, req *RestQueryUserRequest) (*RestQueryUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryUser not implemented")
}
func (*UnimplementedRestQueryServer) QueryUserRelation(ctx context.Context, req *RestQueryUserRelationRequest) (*RestQueryUserRelationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryUserRelation not implemented")
}

func RegisterRestQueryServer(s grpc1.Server, srv RestQueryServer) {
	s.RegisterService(&_RestQuery_serviceDesc, srv)
}

func _RestQuery_QueryDid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestQueryDidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestQueryServer).QueryDid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/misesid.misestm.misestm.RestQuery/QueryDid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestQueryServer).QueryDid(ctx, req.(*RestQueryDidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestQuery_QueryUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestQueryUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestQueryServer).QueryUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/misesid.misestm.misestm.RestQuery/QueryUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestQueryServer).QueryUser(ctx, req.(*RestQueryUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestQuery_QueryUserRelation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestQueryUserRelationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestQueryServer).QueryUserRelation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/misesid.misestm.misestm.RestQuery/QueryUserRelation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestQueryServer).QueryUserRelation(ctx, req.(*RestQueryUserRelationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RestQuery_serviceDesc = grpc.ServiceDesc{
	ServiceName: "misesid.misestm.misestm.RestQuery",
	HandlerType: (*RestQueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryDid",
			Handler:    _RestQuery_QueryDid_Handler,
		},
		{
			MethodName: "QueryUser",
			Handler:    _RestQuery_QueryUser_Handler,
		},
		{
			MethodName: "QueryUserRelation",
			Handler:    _RestQuery_QueryUserRelation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "misestm/rest_query.proto",
}

func (m *RestQueryDidRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RestQueryDidRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RestQueryDidRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MisesId) > 0 {
		i -= len(m.MisesId)
		copy(dAtA[i:], m.MisesId)
		i = encodeVarintRestQuery(dAtA, i, uint64(len(m.MisesId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RestQueryDidResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RestQueryDidResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RestQueryDidResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DidRegistry != nil {
		{
			size, err := m.DidRegistry.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRestQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RestQueryUserRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RestQueryUserRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RestQueryUserRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MisesId) > 0 {
		i -= len(m.MisesId)
		copy(dAtA[i:], m.MisesId)
		i = encodeVarintRestQuery(dAtA, i, uint64(len(m.MisesId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RestQueryUserResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RestQueryUserResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RestQueryUserResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UserInfo != nil {
		{
			size, err := m.UserInfo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRestQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RestQueryUserRelationRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RestQueryUserRelationRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RestQueryUserRelationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRestQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Filter) > 0 {
		i -= len(m.Filter)
		copy(dAtA[i:], m.Filter)
		i = encodeVarintRestQuery(dAtA, i, uint64(len(m.Filter)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.MisesId) > 0 {
		i -= len(m.MisesId)
		copy(dAtA[i:], m.MisesId)
		i = encodeVarintRestQuery(dAtA, i, uint64(len(m.MisesId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RestQueryUserRelationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RestQueryUserRelationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RestQueryUserRelationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRestQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.UserRelation) > 0 {
		for iNdEx := len(m.UserRelation) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.UserRelation[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintRestQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintRestQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovRestQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *RestQueryDidRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MisesId)
	if l > 0 {
		n += 1 + l + sovRestQuery(uint64(l))
	}
	return n
}

func (m *RestQueryDidResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DidRegistry != nil {
		l = m.DidRegistry.Size()
		n += 1 + l + sovRestQuery(uint64(l))
	}
	return n
}

func (m *RestQueryUserRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MisesId)
	if l > 0 {
		n += 1 + l + sovRestQuery(uint64(l))
	}
	return n
}

func (m *RestQueryUserResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.UserInfo != nil {
		l = m.UserInfo.Size()
		n += 1 + l + sovRestQuery(uint64(l))
	}
	return n
}

func (m *RestQueryUserRelationRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MisesId)
	if l > 0 {
		n += 1 + l + sovRestQuery(uint64(l))
	}
	l = len(m.Filter)
	if l > 0 {
		n += 1 + l + sovRestQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovRestQuery(uint64(l))
	}
	return n
}

func (m *RestQueryUserRelationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.UserRelation) > 0 {
		for _, e := range m.UserRelation {
			l = e.Size()
			n += 1 + l + sovRestQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovRestQuery(uint64(l))
	}
	return n
}

func sovRestQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozRestQuery(x uint64) (n int) {
	return sovRestQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RestQueryDidRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRestQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RestQueryDidRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RestQueryDidRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MisesId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRestQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRestQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRestQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MisesId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRestQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRestQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RestQueryDidResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRestQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RestQueryDidResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RestQueryDidResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DidRegistry", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRestQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRestQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRestQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DidRegistry == nil {
				m.DidRegistry = &DidRegistry{}
			}
			if err := m.DidRegistry.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRestQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRestQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RestQueryUserRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRestQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RestQueryUserRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RestQueryUserRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MisesId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRestQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRestQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRestQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MisesId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRestQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRestQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RestQueryUserResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRestQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RestQueryUserResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RestQueryUserResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRestQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRestQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRestQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UserInfo == nil {
				m.UserInfo = &UserInfo{}
			}
			if err := m.UserInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRestQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRestQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RestQueryUserRelationRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRestQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RestQueryUserRelationRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RestQueryUserRelationRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MisesId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRestQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRestQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRestQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MisesId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Filter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRestQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRestQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRestQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Filter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRestQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRestQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRestQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRestQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRestQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RestQueryUserRelationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRestQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RestQueryUserRelationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RestQueryUserRelationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserRelation", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRestQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRestQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRestQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserRelation = append(m.UserRelation, &UserRelation{})
			if err := m.UserRelation[len(m.UserRelation)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRestQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRestQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRestQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRestQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRestQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRestQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRestQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRestQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRestQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthRestQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupRestQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthRestQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthRestQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRestQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupRestQuery = fmt.Errorf("proto: unexpected end of group")
)
