// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: misestm/v1beta1/rest_query.proto

package types

import (
	context "context"
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type RestQueryDidRequest struct {
	MisesId string `protobuf:"bytes,1,opt,name=mises_id,json=misesId,proto3" json:"mises_id,omitempty"`
}

func (m *RestQueryDidRequest) Reset()         { *m = RestQueryDidRequest{} }
func (m *RestQueryDidRequest) String() string { return proto.CompactTextString(m) }
func (*RestQueryDidRequest) ProtoMessage()    {}
func (*RestQueryDidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2297eb53b474b55, []int{0}
}
func (m *RestQueryDidRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RestQueryDidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RestQueryDidRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RestQueryDidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestQueryDidRequest.Merge(m, src)
}
func (m *RestQueryDidRequest) XXX_Size() int {
	return m.Size()
}
func (m *RestQueryDidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestQueryDidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestQueryDidRequest proto.InternalMessageInfo

func (m *RestQueryDidRequest) GetMisesId() string {
	if m != nil {
		return m.MisesId
	}
	return ""
}

type RestQueryDidResponse struct {
	DidRegistry *DidRegistry `protobuf:"bytes,1,opt,name=didRegistry,proto3" json:"didRegistry,omitempty"`
}

func (m *RestQueryDidResponse) Reset()         { *m = RestQueryDidResponse{} }
func (m *RestQueryDidResponse) String() string { return proto.CompactTextString(m) }
func (*RestQueryDidResponse) ProtoMessage()    {}
func (*RestQueryDidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2297eb53b474b55, []int{1}
}
func (m *RestQueryDidResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RestQueryDidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RestQueryDidResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RestQueryDidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestQueryDidResponse.Merge(m, src)
}
func (m *RestQueryDidResponse) XXX_Size() int {
	return m.Size()
}
func (m *RestQueryDidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RestQueryDidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RestQueryDidResponse proto.InternalMessageInfo

func (m *RestQueryDidResponse) GetDidRegistry() *DidRegistry {
	if m != nil {
		return m.DidRegistry
	}
	return nil
}

type RestQueryUserRequest struct {
	MisesUid string `protobuf:"bytes,1,opt,name=mises_uid,json=misesUid,proto3" json:"mises_uid,omitempty"`
}

func (m *RestQueryUserRequest) Reset()         { *m = RestQueryUserRequest{} }
func (m *RestQueryUserRequest) String() string { return proto.CompactTextString(m) }
func (*RestQueryUserRequest) ProtoMessage()    {}
func (*RestQueryUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2297eb53b474b55, []int{2}
}
func (m *RestQueryUserRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RestQueryUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RestQueryUserRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RestQueryUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestQueryUserRequest.Merge(m, src)
}
func (m *RestQueryUserRequest) XXX_Size() int {
	return m.Size()
}
func (m *RestQueryUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestQueryUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestQueryUserRequest proto.InternalMessageInfo

func (m *RestQueryUserRequest) GetMisesUid() string {
	if m != nil {
		return m.MisesUid
	}
	return ""
}

type RestQueryUserResponse struct {
	PubInfo *PublicUserInfo  `protobuf:"bytes,1,opt,name=pub_info,json=pubInfo,proto3" json:"pub_info,omitempty"`
	PriInfo *PrivateUserInfo `protobuf:"bytes,2,opt,name=pri_info,json=priInfo,proto3" json:"pri_info,omitempty"`
	Version uint64           `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
}

func (m *RestQueryUserResponse) Reset()         { *m = RestQueryUserResponse{} }
func (m *RestQueryUserResponse) String() string { return proto.CompactTextString(m) }
func (*RestQueryUserResponse) ProtoMessage()    {}
func (*RestQueryUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2297eb53b474b55, []int{3}
}
func (m *RestQueryUserResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RestQueryUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RestQueryUserResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RestQueryUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestQueryUserResponse.Merge(m, src)
}
func (m *RestQueryUserResponse) XXX_Size() int {
	return m.Size()
}
func (m *RestQueryUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RestQueryUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RestQueryUserResponse proto.InternalMessageInfo

func (m *RestQueryUserResponse) GetPubInfo() *PublicUserInfo {
	if m != nil {
		return m.PubInfo
	}
	return nil
}

func (m *RestQueryUserResponse) GetPriInfo() *PrivateUserInfo {
	if m != nil {
		return m.PriInfo
	}
	return nil
}

func (m *RestQueryUserResponse) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

type RestQueryUserRelationRequest struct {
	MisesUid   string             `protobuf:"bytes,1,opt,name=mises_uid,json=misesUid,proto3" json:"mises_uid,omitempty"`
	Filter     string             `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *RestQueryUserRelationRequest) Reset()         { *m = RestQueryUserRelationRequest{} }
func (m *RestQueryUserRelationRequest) String() string { return proto.CompactTextString(m) }
func (*RestQueryUserRelationRequest) ProtoMessage()    {}
func (*RestQueryUserRelationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2297eb53b474b55, []int{4}
}
func (m *RestQueryUserRelationRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RestQueryUserRelationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RestQueryUserRelationRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RestQueryUserRelationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestQueryUserRelationRequest.Merge(m, src)
}
func (m *RestQueryUserRelationRequest) XXX_Size() int {
	return m.Size()
}
func (m *RestQueryUserRelationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestQueryUserRelationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestQueryUserRelationRequest proto.InternalMessageInfo

func (m *RestQueryUserRelationRequest) GetMisesUid() string {
	if m != nil {
		return m.MisesUid
	}
	return ""
}

func (m *RestQueryUserRelationRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *RestQueryUserRelationRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type MisesID struct {
	MisesId string `protobuf:"bytes,1,opt,name=mises_id,json=misesId,proto3" json:"mises_id,omitempty"`
	RelType string `protobuf:"bytes,2,opt,name=rel_type,json=relType,proto3" json:"rel_type,omitempty"`
}

func (m *MisesID) Reset()         { *m = MisesID{} }
func (m *MisesID) String() string { return proto.CompactTextString(m) }
func (*MisesID) ProtoMessage()    {}
func (*MisesID) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2297eb53b474b55, []int{5}
}
func (m *MisesID) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MisesID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MisesID.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MisesID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MisesID.Merge(m, src)
}
func (m *MisesID) XXX_Size() int {
	return m.Size()
}
func (m *MisesID) XXX_DiscardUnknown() {
	xxx_messageInfo_MisesID.DiscardUnknown(m)
}

var xxx_messageInfo_MisesID proto.InternalMessageInfo

func (m *MisesID) GetMisesId() string {
	if m != nil {
		return m.MisesId
	}
	return ""
}

func (m *MisesID) GetRelType() string {
	if m != nil {
		return m.RelType
	}
	return ""
}

type RestQueryUserRelationResponse struct {
	MisesList  []*MisesID          `protobuf:"bytes,1,rep,name=mises_list,json=misesList,proto3" json:"mises_list,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *RestQueryUserRelationResponse) Reset()         { *m = RestQueryUserRelationResponse{} }
func (m *RestQueryUserRelationResponse) String() string { return proto.CompactTextString(m) }
func (*RestQueryUserRelationResponse) ProtoMessage()    {}
func (*RestQueryUserRelationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2297eb53b474b55, []int{6}
}
func (m *RestQueryUserRelationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RestQueryUserRelationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RestQueryUserRelationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RestQueryUserRelationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestQueryUserRelationResponse.Merge(m, src)
}
func (m *RestQueryUserRelationResponse) XXX_Size() int {
	return m.Size()
}
func (m *RestQueryUserRelationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RestQueryUserRelationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RestQueryUserRelationResponse proto.InternalMessageInfo

func (m *RestQueryUserRelationResponse) GetMisesList() []*MisesID {
	if m != nil {
		return m.MisesList
	}
	return nil
}

func (m *RestQueryUserRelationResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type RestQueryAppRequest struct {
	MisesAppid string `protobuf:"bytes,1,opt,name=mises_appid,json=misesAppid,proto3" json:"mises_appid,omitempty"`
}

func (m *RestQueryAppRequest) Reset()         { *m = RestQueryAppRequest{} }
func (m *RestQueryAppRequest) String() string { return proto.CompactTextString(m) }
func (*RestQueryAppRequest) ProtoMessage()    {}
func (*RestQueryAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2297eb53b474b55, []int{7}
}
func (m *RestQueryAppRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RestQueryAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RestQueryAppRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RestQueryAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestQueryAppRequest.Merge(m, src)
}
func (m *RestQueryAppRequest) XXX_Size() int {
	return m.Size()
}
func (m *RestQueryAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestQueryAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestQueryAppRequest proto.InternalMessageInfo

func (m *RestQueryAppRequest) GetMisesAppid() string {
	if m != nil {
		return m.MisesAppid
	}
	return ""
}

type RestQueryAppResponse struct {
	PubInfo *PublicAppInfo `protobuf:"bytes,1,opt,name=pub_info,json=pubInfo,proto3" json:"pub_info,omitempty"`
	Version uint64         `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (m *RestQueryAppResponse) Reset()         { *m = RestQueryAppResponse{} }
func (m *RestQueryAppResponse) String() string { return proto.CompactTextString(m) }
func (*RestQueryAppResponse) ProtoMessage()    {}
func (*RestQueryAppResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2297eb53b474b55, []int{8}
}
func (m *RestQueryAppResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RestQueryAppResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RestQueryAppResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RestQueryAppResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestQueryAppResponse.Merge(m, src)
}
func (m *RestQueryAppResponse) XXX_Size() int {
	return m.Size()
}
func (m *RestQueryAppResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RestQueryAppResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RestQueryAppResponse proto.InternalMessageInfo

func (m *RestQueryAppResponse) GetPubInfo() *PublicAppInfo {
	if m != nil {
		return m.PubInfo
	}
	return nil
}

func (m *RestQueryAppResponse) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

type RestQueryTxRequest struct {
	Txhash string `protobuf:"bytes,1,opt,name=txhash,proto3" json:"txhash,omitempty"`
}

func (m *RestQueryTxRequest) Reset()         { *m = RestQueryTxRequest{} }
func (m *RestQueryTxRequest) String() string { return proto.CompactTextString(m) }
func (*RestQueryTxRequest) ProtoMessage()    {}
func (*RestQueryTxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2297eb53b474b55, []int{9}
}
func (m *RestQueryTxRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RestQueryTxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RestQueryTxRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RestQueryTxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestQueryTxRequest.Merge(m, src)
}
func (m *RestQueryTxRequest) XXX_Size() int {
	return m.Size()
}
func (m *RestQueryTxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestQueryTxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestQueryTxRequest proto.InternalMessageInfo

func (m *RestQueryTxRequest) GetTxhash() string {
	if m != nil {
		return m.Txhash
	}
	return ""
}

type RestTxResponse struct {
	// tx_response is the queried TxResponses.
	TxResponse *types.TxResponse `protobuf:"bytes,1,opt,name=tx_response,json=txResponse,proto3" json:"tx_response,omitempty"`
	Code       uint32            `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (m *RestTxResponse) Reset()         { *m = RestTxResponse{} }
func (m *RestTxResponse) String() string { return proto.CompactTextString(m) }
func (*RestTxResponse) ProtoMessage()    {}
func (*RestTxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2297eb53b474b55, []int{10}
}
func (m *RestTxResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RestTxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RestTxResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RestTxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestTxResponse.Merge(m, src)
}
func (m *RestTxResponse) XXX_Size() int {
	return m.Size()
}
func (m *RestTxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RestTxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RestTxResponse proto.InternalMessageInfo

func (m *RestTxResponse) GetTxResponse() *types.TxResponse {
	if m != nil {
		return m.TxResponse
	}
	return nil
}

func (m *RestTxResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type RestQueryAppFeeGrantRequest struct {
	MisesAppid string `protobuf:"bytes,1,opt,name=mises_appid,json=misesAppid,proto3" json:"mises_appid,omitempty"`
	MisesUid   string `protobuf:"bytes,2,opt,name=mises_uid,json=misesUid,proto3" json:"mises_uid,omitempty"`
}

func (m *RestQueryAppFeeGrantRequest) Reset()         { *m = RestQueryAppFeeGrantRequest{} }
func (m *RestQueryAppFeeGrantRequest) String() string { return proto.CompactTextString(m) }
func (*RestQueryAppFeeGrantRequest) ProtoMessage()    {}
func (*RestQueryAppFeeGrantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2297eb53b474b55, []int{11}
}
func (m *RestQueryAppFeeGrantRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RestQueryAppFeeGrantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RestQueryAppFeeGrantRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RestQueryAppFeeGrantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestQueryAppFeeGrantRequest.Merge(m, src)
}
func (m *RestQueryAppFeeGrantRequest) XXX_Size() int {
	return m.Size()
}
func (m *RestQueryAppFeeGrantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestQueryAppFeeGrantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestQueryAppFeeGrantRequest proto.InternalMessageInfo

func (m *RestQueryAppFeeGrantRequest) GetMisesAppid() string {
	if m != nil {
		return m.MisesAppid
	}
	return ""
}

func (m *RestQueryAppFeeGrantRequest) GetMisesUid() string {
	if m != nil {
		return m.MisesUid
	}
	return ""
}

type AppFeeGrant struct {
	SpendLimit *types.Coin   `protobuf:"bytes,1,opt,name=spend_limit,json=spendLimit,proto3" json:"spend_limit,omitempty"`
	Period     time.Duration `protobuf:"bytes,2,opt,name=period,proto3,stdduration" json:"period"`
	Expiration *time.Time    `protobuf:"bytes,3,opt,name=expiration,proto3,stdtime" json:"expiration,omitempty"`
}

func (m *AppFeeGrant) Reset()         { *m = AppFeeGrant{} }
func (m *AppFeeGrant) String() string { return proto.CompactTextString(m) }
func (*AppFeeGrant) ProtoMessage()    {}
func (*AppFeeGrant) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2297eb53b474b55, []int{12}
}
func (m *AppFeeGrant) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AppFeeGrant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AppFeeGrant.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AppFeeGrant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppFeeGrant.Merge(m, src)
}
func (m *AppFeeGrant) XXX_Size() int {
	return m.Size()
}
func (m *AppFeeGrant) XXX_DiscardUnknown() {
	xxx_messageInfo_AppFeeGrant.DiscardUnknown(m)
}

var xxx_messageInfo_AppFeeGrant proto.InternalMessageInfo

func (m *AppFeeGrant) GetSpendLimit() *types.Coin {
	if m != nil {
		return m.SpendLimit
	}
	return nil
}

func (m *AppFeeGrant) GetPeriod() time.Duration {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *AppFeeGrant) GetExpiration() *time.Time {
	if m != nil {
		return m.Expiration
	}
	return nil
}

type RestQueryAppFeeGrantResponse struct {
	Grant *AppFeeGrant `protobuf:"bytes,1,opt,name=grant,proto3" json:"grant,omitempty"`
}

func (m *RestQueryAppFeeGrantResponse) Reset()         { *m = RestQueryAppFeeGrantResponse{} }
func (m *RestQueryAppFeeGrantResponse) String() string { return proto.CompactTextString(m) }
func (*RestQueryAppFeeGrantResponse) ProtoMessage()    {}
func (*RestQueryAppFeeGrantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2297eb53b474b55, []int{13}
}
func (m *RestQueryAppFeeGrantResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RestQueryAppFeeGrantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RestQueryAppFeeGrantResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RestQueryAppFeeGrantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestQueryAppFeeGrantResponse.Merge(m, src)
}
func (m *RestQueryAppFeeGrantResponse) XXX_Size() int {
	return m.Size()
}
func (m *RestQueryAppFeeGrantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RestQueryAppFeeGrantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RestQueryAppFeeGrantResponse proto.InternalMessageInfo

func (m *RestQueryAppFeeGrantResponse) GetGrant() *AppFeeGrant {
	if m != nil {
		return m.Grant
	}
	return nil
}

func init() {
	proto.RegisterType((*RestQueryDidRequest)(nil), "misesid.misestm.v1beta1.RestQueryDidRequest")
	proto.RegisterType((*RestQueryDidResponse)(nil), "misesid.misestm.v1beta1.RestQueryDidResponse")
	proto.RegisterType((*RestQueryUserRequest)(nil), "misesid.misestm.v1beta1.RestQueryUserRequest")
	proto.RegisterType((*RestQueryUserResponse)(nil), "misesid.misestm.v1beta1.RestQueryUserResponse")
	proto.RegisterType((*RestQueryUserRelationRequest)(nil), "misesid.misestm.v1beta1.RestQueryUserRelationRequest")
	proto.RegisterType((*MisesID)(nil), "misesid.misestm.v1beta1.MisesID")
	proto.RegisterType((*RestQueryUserRelationResponse)(nil), "misesid.misestm.v1beta1.RestQueryUserRelationResponse")
	proto.RegisterType((*RestQueryAppRequest)(nil), "misesid.misestm.v1beta1.RestQueryAppRequest")
	proto.RegisterType((*RestQueryAppResponse)(nil), "misesid.misestm.v1beta1.RestQueryAppResponse")
	proto.RegisterType((*RestQueryTxRequest)(nil), "misesid.misestm.v1beta1.RestQueryTxRequest")
	proto.RegisterType((*RestTxResponse)(nil), "misesid.misestm.v1beta1.RestTxResponse")
	proto.RegisterType((*RestQueryAppFeeGrantRequest)(nil), "misesid.misestm.v1beta1.RestQueryAppFeeGrantRequest")
	proto.RegisterType((*AppFeeGrant)(nil), "misesid.misestm.v1beta1.AppFeeGrant")
	proto.RegisterType((*RestQueryAppFeeGrantResponse)(nil), "misesid.misestm.v1beta1.RestQueryAppFeeGrantResponse")
}

func init() { proto.RegisterFile("misestm/v1beta1/rest_query.proto", fileDescriptor_c2297eb53b474b55) }

var fileDescriptor_c2297eb53b474b55 = []byte{
	// 1009 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0x4d, 0x6f, 0x1b, 0x45,
	0x18, 0xce, 0xba, 0xc1, 0x1f, 0xef, 0x52, 0x44, 0x27, 0x69, 0x48, 0x9c, 0xd4, 0x31, 0x0b, 0x6a,
	0x23, 0x48, 0x77, 0x69, 0x4a, 0x7b, 0x28, 0x87, 0xe2, 0x34, 0xa4, 0xaa, 0x54, 0x24, 0x58, 0xa5,
	0x97, 0x22, 0x61, 0xad, 0xbd, 0x63, 0x67, 0x84, 0xbd, 0x33, 0x9d, 0x99, 0x8d, 0x1c, 0x71, 0x40,
	0xe2, 0x17, 0x54, 0xe2, 0x82, 0x04, 0x07, 0xae, 0xfc, 0x05, 0xc4, 0x0f, 0xc8, 0xb1, 0x12, 0x17,
	0x4e, 0x80, 0x12, 0x7e, 0x48, 0xb5, 0x33, 0xb3, 0xeb, 0xb1, 0x53, 0x37, 0xee, 0x6d, 0xc7, 0xf3,
	0xbc, 0xcf, 0xfb, 0xbc, 0x9f, 0x63, 0x68, 0x0e, 0x89, 0xc0, 0x42, 0x0e, 0x83, 0xa3, 0x5b, 0x1d,
	0x2c, 0xa3, 0x5b, 0x01, 0xc7, 0x42, 0xb6, 0x9f, 0xa5, 0x98, 0x1f, 0xfb, 0x8c, 0x53, 0x49, 0xd1,
	0x7b, 0x0a, 0x41, 0x62, 0xdf, 0x20, 0x7d, 0x83, 0xac, 0x2f, 0xf7, 0x69, 0x9f, 0x2a, 0x4c, 0x90,
	0x7d, 0x69, 0x78, 0x7d, 0xa3, 0x4f, 0x69, 0x7f, 0x80, 0x83, 0x88, 0x91, 0x20, 0x4a, 0x12, 0x2a,
	0x23, 0x49, 0x68, 0x22, 0xcc, 0x6d, 0xc3, 0xdc, 0xaa, 0x53, 0x27, 0xed, 0x05, 0x71, 0xca, 0x15,
	0xc0, 0xdc, 0x6f, 0x4e, 0xdf, 0x4b, 0x32, 0xc4, 0x42, 0x46, 0x43, 0x66, 0x00, 0x1f, 0x75, 0xa9,
	0x18, 0x52, 0x11, 0x74, 0x22, 0x81, 0x03, 0x25, 0xb3, 0x50, 0xce, 0xa2, 0x3e, 0x49, 0x6c, 0xb2,
	0x0f, 0x6c, 0x6c, 0xd4, 0xe9, 0x92, 0x02, 0x9a, 0x1d, 0x72, 0x45, 0x36, 0x28, 0xbf, 0xef, 0x52,
	0x92, 0x93, 0xbc, 0x3f, 0x9d, 0xa0, 0x3d, 0x12, 0x87, 0xb8, 0x4f, 0x84, 0xcc, 0x33, 0x54, 0x6f,
	0x4c, 0x43, 0x9e, 0x08, 0xcc, 0x1f, 0x25, 0xbd, 0x3c, 0x25, 0xde, 0xab, 0xee, 0x43, 0x3c, 0xb0,
	0xb5, 0x5e, 0x9b, 0xc6, 0xb4, 0x18, 0x1b, 0x53, 0x78, 0x9f, 0xc0, 0x52, 0x88, 0x85, 0xfc, 0x3a,
	0x0b, 0x58, 0x09, 0x78, 0x96, 0x62, 0x21, 0xd1, 0x1a, 0x54, 0x95, 0x5d, 0x9b, 0xc4, 0xab, 0x4e,
	0xd3, 0xd9, 0xaa, 0x85, 0x15, 0x75, 0x7e, 0x14, 0x7b, 0xdf, 0xc2, 0xf2, 0xa4, 0x85, 0x60, 0x34,
	0x11, 0x18, 0xed, 0x83, 0x1b, 0x8f, 0x23, 0x50, 0x56, 0xee, 0xce, 0x87, 0xfe, 0x8c, 0x22, 0xfb,
	0x56, 0xb4, 0xa1, 0x6d, 0xe8, 0xdd, 0xb6, 0xf8, 0x75, 0x3c, 0x5a, 0xd2, 0x3a, 0xd4, 0xb4, 0xa4,
	0xb4, 0xd0, 0xa4, 0x35, 0x3e, 0x21, 0xb1, 0xf7, 0x87, 0x03, 0x57, 0xa7, 0xac, 0x8c, 0xac, 0x5d,
	0xa8, 0xb2, 0xb4, 0xd3, 0x26, 0x49, 0x8f, 0x1a, 0x4d, 0x37, 0x66, 0x6a, 0xfa, 0x2a, 0xed, 0x0c,
	0x48, 0x37, 0x4f, 0x72, 0x58, 0x61, 0x69, 0x27, 0xfb, 0x40, 0x0f, 0xa0, 0xca, 0x38, 0xd1, 0x1c,
	0x25, 0xc5, 0xb1, 0x35, 0x9b, 0x83, 0x93, 0xa3, 0x48, 0x62, 0x8b, 0x84, 0x13, 0x45, 0xb2, 0x0a,
	0x95, 0x23, 0xcc, 0x05, 0xa1, 0xc9, 0xea, 0xa5, 0xa6, 0xb3, 0xb5, 0x18, 0xe6, 0x47, 0xef, 0x17,
	0x07, 0x36, 0xa6, 0xc4, 0xeb, 0x12, 0xce, 0x13, 0x3a, 0x5a, 0x81, 0x72, 0x8f, 0x0c, 0x24, 0xe6,
	0x4a, 0x5a, 0x2d, 0x34, 0x27, 0xb4, 0x0f, 0x30, 0x6e, 0x5c, 0xe5, 0xd2, 0xdd, 0xb9, 0xee, 0xeb,
	0xa6, 0xf4, 0xb3, 0xa6, 0xf4, 0xf5, 0x30, 0x16, 0xc2, 0xa3, 0x3e, 0x36, 0x0e, 0x43, 0xcb, 0xd2,
	0xbb, 0x0f, 0x95, 0x2f, 0x55, 0xe9, 0xf7, 0x5e, 0xd3, 0x15, 0xd9, 0x15, 0xc7, 0x83, 0xb6, 0x3c,
	0x66, 0xd8, 0xe8, 0xa8, 0x70, 0x3c, 0x38, 0x38, 0x66, 0xd8, 0xfb, 0xdd, 0x81, 0x6b, 0x33, 0xc2,
	0x33, 0x35, 0xba, 0x0f, 0xa0, 0x79, 0x07, 0x44, 0xc8, 0x55, 0xa7, 0x79, 0x69, 0xcb, 0xdd, 0x69,
	0xce, 0xcc, 0xb0, 0x51, 0x13, 0xea, 0x9c, 0x3c, 0x26, 0x42, 0xa2, 0x87, 0x13, 0xb1, 0x96, 0x4c,
	0x99, 0x2f, 0x8a, 0x55, 0x7b, 0x9f, 0x08, 0xf6, 0xae, 0x35, 0x0e, 0x2d, 0xc6, 0xf2, 0x02, 0x6c,
	0x82, 0xab, 0x05, 0x46, 0x8c, 0x15, 0xb1, 0x6b, 0xcd, 0xad, 0xec, 0x17, 0x4f, 0x58, 0x4d, 0xab,
	0xec, 0x4c, 0x64, 0xad, 0x73, 0xdd, 0x77, 0xfd, 0x82, 0xee, 0x33, 0xe3, 0x39, 0x6e, 0x3e, 0xab,
	0x6f, 0x4a, 0x93, 0x7d, 0xb3, 0x0d, 0xa8, 0x70, 0x7a, 0x30, 0xca, 0xb5, 0xae, 0x40, 0x59, 0x8e,
	0x0e, 0x23, 0x71, 0x68, 0x64, 0x9a, 0x93, 0xf7, 0x1d, 0xbc, 0x93, 0xa1, 0x33, 0xa0, 0x11, 0xf7,
	0x05, 0xb8, 0x72, 0xd4, 0xe6, 0xe6, 0x58, 0x4c, 0xac, 0x9d, 0x36, 0xb5, 0xcf, 0x72, 0x81, 0x63,
	0xd3, 0x10, 0xe4, 0x98, 0x06, 0xc1, 0x62, 0x97, 0xc6, 0xba, 0xec, 0x97, 0x43, 0xf5, 0xed, 0x7d,
	0x03, 0xeb, 0x76, 0x3e, 0xf6, 0x31, 0x7e, 0xc8, 0xa3, 0x44, 0xce, 0x9b, 0xcf, 0xc9, 0x8e, 0x2f,
	0x4d, 0x0d, 0xfb, 0x89, 0x03, 0xae, 0x45, 0x8a, 0xee, 0x81, 0x2b, 0x18, 0x4e, 0xe2, 0xf6, 0x80,
	0x0c, 0x89, 0x34, 0x71, 0xac, 0x4d, 0xc4, 0x91, 0x87, 0xf0, 0x80, 0x92, 0x24, 0x04, 0x85, 0x7e,
	0x9c, 0x81, 0xd1, 0x67, 0x50, 0x66, 0x98, 0x13, 0x1a, 0x9b, 0xae, 0x59, 0xf3, 0xf5, 0x43, 0xe1,
	0xe7, 0x0f, 0x85, 0xbf, 0x67, 0x1e, 0x92, 0xdd, 0xea, 0xc9, 0x3f, 0x9b, 0x0b, 0x3f, 0xff, 0xbb,
	0xe9, 0x84, 0xc6, 0x04, 0x7d, 0x0e, 0x80, 0x47, 0x8c, 0x70, 0x7b, 0xc4, 0xea, 0xe7, 0x08, 0x0e,
	0xf2, 0x97, 0x66, 0x77, 0xf1, 0x79, 0x66, 0x6d, 0xd9, 0x78, 0x4f, 0xad, 0xc9, 0x9f, 0xc8, 0x93,
	0xc9, 0xed, 0x3d, 0x78, 0xab, 0x9f, 0xfd, 0x70, 0xe1, 0x3a, 0xb5, 0x8d, 0xb5, 0xc9, 0xce, 0x9f,
	0x65, 0xa8, 0x15, 0xe4, 0xe8, 0x7b, 0xa8, 0xe6, 0x2b, 0x1b, 0x6d, 0xcf, 0xa4, 0x79, 0xc5, 0x5b,
	0x50, 0xbf, 0x39, 0x27, 0x5a, 0x4b, 0xf6, 0xd0, 0x8f, 0x7f, 0xfd, 0xff, 0x53, 0xe9, 0x6d, 0x04,
	0x81, 0x82, 0x07, 0x31, 0x89, 0xd1, 0x0f, 0x50, 0x2b, 0xa6, 0x1f, 0xcd, 0xc1, 0x67, 0xed, 0xfd,
	0xba, 0x3f, 0x2f, 0xdc, 0xf8, 0x5f, 0x52, 0xfe, 0x2f, 0x23, 0xd7, 0xf8, 0x4f, 0x33, 0x9f, 0xbf,
	0x39, 0x70, 0xe5, 0xdc, 0xfe, 0x41, 0x77, 0xe6, 0xa5, 0x9e, 0x58, 0xc7, 0xf5, 0xbb, 0x6f, 0x6a,
	0x66, 0x94, 0x6d, 0x28, 0x65, 0x2b, 0x68, 0xd9, 0x52, 0x16, 0xf0, 0x5c, 0x4c, 0x5e, 0xa0, 0x16,
	0x63, 0xf3, 0x14, 0x68, 0xbc, 0x9d, 0xe6, 0x29, 0x90, 0xb5, 0x93, 0xce, 0x15, 0x28, 0x62, 0x0c,
	0xfd, 0xea, 0xc0, 0xbb, 0xd3, 0x4d, 0x88, 0x3e, 0x9d, 0x8b, 0x77, 0x6a, 0xb6, 0xeb, 0x77, 0xde,
	0xd0, 0xca, 0xa8, 0x5a, 0x57, 0xaa, 0xae, 0xa2, 0xa5, 0xb1, 0xaa, 0xa0, 0x87, 0xb1, 0x6a, 0x65,
	0xc4, 0xa1, 0x62, 0xb6, 0x1c, 0xfa, 0xf8, 0x62, 0xfa, 0x62, 0x17, 0xd6, 0x6f, 0xbc, 0x16, 0x3c,
	0xde, 0x67, 0xde, 0x15, 0xe5, 0xdd, 0x45, 0x35, 0xe3, 0x5d, 0x8e, 0x76, 0xf7, 0x4f, 0x4e, 0x1b,
	0xce, 0x8b, 0xd3, 0x86, 0xf3, 0xdf, 0x69, 0xc3, 0x79, 0x7e, 0xd6, 0x58, 0x78, 0x71, 0xd6, 0x58,
	0xf8, 0xfb, 0xac, 0xb1, 0xf0, 0x74, 0xbb, 0x4f, 0xe4, 0x61, 0xda, 0xf1, 0xbb, 0x74, 0xa8, 0xe1,
	0x37, 0x49, 0x6c, 0x3e, 0xe4, 0x30, 0x18, 0x05, 0xf9, 0x3f, 0xae, 0xec, 0x31, 0x14, 0x9d, 0xb2,
	0x5a, 0x04, 0xb7, 0x5f, 0x06, 0x00, 0x00, 0xff, 0xff, 0x13, 0x59, 0x48, 0x14, 0x11, 0x0b, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RestQueryClient is the client API for RestQuery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RestQueryClient interface {
	// query a did
	QueryDid(ctx context.Context, in *RestQueryDidRequest, opts ...grpc.CallOption) (*RestQueryDidResponse, error)
	// query a user info
	QueryUser(ctx context.Context, in *RestQueryUserRequest, opts ...grpc.CallOption) (*RestQueryUserResponse, error)
	// query user relations
	QueryUserRelation(ctx context.Context, in *RestQueryUserRelationRequest, opts ...grpc.CallOption) (*RestQueryUserRelationResponse, error)
	// query app info
	QueryApp(ctx context.Context, in *RestQueryAppRequest, opts ...grpc.CallOption) (*RestQueryAppResponse, error)
	// query app info
	QueryAppFeeGrant(ctx context.Context, in *RestQueryAppFeeGrantRequest, opts ...grpc.CallOption) (*RestQueryAppFeeGrantResponse, error)
	// query a tx result
	QueryTx(ctx context.Context, in *RestQueryTxRequest, opts ...grpc.CallOption) (*RestTxResponse, error)
}

type restQueryClient struct {
	cc grpc1.ClientConn
}

func NewRestQueryClient(cc grpc1.ClientConn) RestQueryClient {
	return &restQueryClient{cc}
}

func (c *restQueryClient) QueryDid(ctx context.Context, in *RestQueryDidRequest, opts ...grpc.CallOption) (*RestQueryDidResponse, error) {
	out := new(RestQueryDidResponse)
	err := c.cc.Invoke(ctx, "/misesid.misestm.v1beta1.RestQuery/QueryDid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restQueryClient) QueryUser(ctx context.Context, in *RestQueryUserRequest, opts ...grpc.CallOption) (*RestQueryUserResponse, error) {
	out := new(RestQueryUserResponse)
	err := c.cc.Invoke(ctx, "/misesid.misestm.v1beta1.RestQuery/QueryUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restQueryClient) QueryUserRelation(ctx context.Context, in *RestQueryUserRelationRequest, opts ...grpc.CallOption) (*RestQueryUserRelationResponse, error) {
	out := new(RestQueryUserRelationResponse)
	err := c.cc.Invoke(ctx, "/misesid.misestm.v1beta1.RestQuery/QueryUserRelation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restQueryClient) QueryApp(ctx context.Context, in *RestQueryAppRequest, opts ...grpc.CallOption) (*RestQueryAppResponse, error) {
	out := new(RestQueryAppResponse)
	err := c.cc.Invoke(ctx, "/misesid.misestm.v1beta1.RestQuery/QueryApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restQueryClient) QueryAppFeeGrant(ctx context.Context, in *RestQueryAppFeeGrantRequest, opts ...grpc.CallOption) (*RestQueryAppFeeGrantResponse, error) {
	out := new(RestQueryAppFeeGrantResponse)
	err := c.cc.Invoke(ctx, "/misesid.misestm.v1beta1.RestQuery/QueryAppFeeGrant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restQueryClient) QueryTx(ctx context.Context, in *RestQueryTxRequest, opts ...grpc.CallOption) (*RestTxResponse, error) {
	out := new(RestTxResponse)
	err := c.cc.Invoke(ctx, "/misesid.misestm.v1beta1.RestQuery/QueryTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RestQueryServer is the server API for RestQuery service.
type RestQueryServer interface {
	// query a did
	QueryDid(context.Context, *RestQueryDidRequest) (*RestQueryDidResponse, error)
	// query a user info
	QueryUser(context.Context, *RestQueryUserRequest) (*RestQueryUserResponse, error)
	// query user relations
	QueryUserRelation(context.Context, *RestQueryUserRelationRequest) (*RestQueryUserRelationResponse, error)
	// query app info
	QueryApp(context.Context, *RestQueryAppRequest) (*RestQueryAppResponse, error)
	// query app info
	QueryAppFeeGrant(context.Context, *RestQueryAppFeeGrantRequest) (*RestQueryAppFeeGrantResponse, error)
	// query a tx result
	QueryTx(context.Context, *RestQueryTxRequest) (*RestTxResponse, error)
}

// UnimplementedRestQueryServer can be embedded to have forward compatible implementations.
type UnimplementedRestQueryServer struct {
}

func (*UnimplementedRestQueryServer) QueryDid(ctx context.Context, req *RestQueryDidRequest) (*RestQueryDidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryDid not implemented")
}
func (*UnimplementedRestQueryServer) QueryUser(ctx context.Context, req *RestQueryUserRequest) (*RestQueryUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryUser not implemented")
}
func (*UnimplementedRestQueryServer) QueryUserRelation(ctx context.Context, req *RestQueryUserRelationRequest) (*RestQueryUserRelationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryUserRelation not implemented")
}
func (*UnimplementedRestQueryServer) QueryApp(ctx context.Context, req *RestQueryAppRequest) (*RestQueryAppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryApp not implemented")
}
func (*UnimplementedRestQueryServer) QueryAppFeeGrant(ctx context.Context, req *RestQueryAppFeeGrantRequest) (*RestQueryAppFeeGrantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryAppFeeGrant not implemented")
}
func (*UnimplementedRestQueryServer) QueryTx(ctx context.Context, req *RestQueryTxRequest) (*RestTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryTx not implemented")
}

func RegisterRestQueryServer(s grpc1.Server, srv RestQueryServer) {
	s.RegisterService(&_RestQuery_serviceDesc, srv)
}

func _RestQuery_QueryDid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestQueryDidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestQueryServer).QueryDid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/misesid.misestm.v1beta1.RestQuery/QueryDid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestQueryServer).QueryDid(ctx, req.(*RestQueryDidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestQuery_QueryUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestQueryUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestQueryServer).QueryUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/misesid.misestm.v1beta1.RestQuery/QueryUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestQueryServer).QueryUser(ctx, req.(*RestQueryUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestQuery_QueryUserRelation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestQueryUserRelationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestQueryServer).QueryUserRelation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/misesid.misestm.v1beta1.RestQuery/QueryUserRelation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestQueryServer).QueryUserRelation(ctx, req.(*RestQueryUserRelationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestQuery_QueryApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestQueryAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestQueryServer).QueryApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/misesid.misestm.v1beta1.RestQuery/QueryApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestQueryServer).QueryApp(ctx, req.(*RestQueryAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestQuery_QueryAppFeeGrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestQueryAppFeeGrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestQueryServer).QueryAppFeeGrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/misesid.misestm.v1beta1.RestQuery/QueryAppFeeGrant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestQueryServer).QueryAppFeeGrant(ctx, req.(*RestQueryAppFeeGrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestQuery_QueryTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestQueryTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestQueryServer).QueryTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/misesid.misestm.v1beta1.RestQuery/QueryTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestQueryServer).QueryTx(ctx, req.(*RestQueryTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RestQuery_serviceDesc = grpc.ServiceDesc{
	ServiceName: "misesid.misestm.v1beta1.RestQuery",
	HandlerType: (*RestQueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryDid",
			Handler:    _RestQuery_QueryDid_Handler,
		},
		{
			MethodName: "QueryUser",
			Handler:    _RestQuery_QueryUser_Handler,
		},
		{
			MethodName: "QueryUserRelation",
			Handler:    _RestQuery_QueryUserRelation_Handler,
		},
		{
			MethodName: "QueryApp",
			Handler:    _RestQuery_QueryApp_Handler,
		},
		{
			MethodName: "QueryAppFeeGrant",
			Handler:    _RestQuery_QueryAppFeeGrant_Handler,
		},
		{
			MethodName: "QueryTx",
			Handler:    _RestQuery_QueryTx_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "misestm/v1beta1/rest_query.proto",
}

func (m *RestQueryDidRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RestQueryDidRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RestQueryDidRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MisesId) > 0 {
		i -= len(m.MisesId)
		copy(dAtA[i:], m.MisesId)
		i = encodeVarintRestQuery(dAtA, i, uint64(len(m.MisesId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RestQueryDidResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RestQueryDidResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RestQueryDidResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DidRegistry != nil {
		{
			size, err := m.DidRegistry.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRestQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RestQueryUserRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RestQueryUserRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RestQueryUserRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MisesUid) > 0 {
		i -= len(m.MisesUid)
		copy(dAtA[i:], m.MisesUid)
		i = encodeVarintRestQuery(dAtA, i, uint64(len(m.MisesUid)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RestQueryUserResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RestQueryUserResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RestQueryUserResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Version != 0 {
		i = encodeVarintRestQuery(dAtA, i, uint64(m.Version))
		i--
		dAtA[i] = 0x18
	}
	if m.PriInfo != nil {
		{
			size, err := m.PriInfo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRestQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.PubInfo != nil {
		{
			size, err := m.PubInfo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRestQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RestQueryUserRelationRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RestQueryUserRelationRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RestQueryUserRelationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRestQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Filter) > 0 {
		i -= len(m.Filter)
		copy(dAtA[i:], m.Filter)
		i = encodeVarintRestQuery(dAtA, i, uint64(len(m.Filter)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.MisesUid) > 0 {
		i -= len(m.MisesUid)
		copy(dAtA[i:], m.MisesUid)
		i = encodeVarintRestQuery(dAtA, i, uint64(len(m.MisesUid)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MisesID) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MisesID) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MisesID) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RelType) > 0 {
		i -= len(m.RelType)
		copy(dAtA[i:], m.RelType)
		i = encodeVarintRestQuery(dAtA, i, uint64(len(m.RelType)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.MisesId) > 0 {
		i -= len(m.MisesId)
		copy(dAtA[i:], m.MisesId)
		i = encodeVarintRestQuery(dAtA, i, uint64(len(m.MisesId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RestQueryUserRelationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RestQueryUserRelationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RestQueryUserRelationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRestQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.MisesList) > 0 {
		for iNdEx := len(m.MisesList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MisesList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintRestQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *RestQueryAppRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RestQueryAppRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RestQueryAppRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MisesAppid) > 0 {
		i -= len(m.MisesAppid)
		copy(dAtA[i:], m.MisesAppid)
		i = encodeVarintRestQuery(dAtA, i, uint64(len(m.MisesAppid)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RestQueryAppResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RestQueryAppResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RestQueryAppResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Version != 0 {
		i = encodeVarintRestQuery(dAtA, i, uint64(m.Version))
		i--
		dAtA[i] = 0x10
	}
	if m.PubInfo != nil {
		{
			size, err := m.PubInfo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRestQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RestQueryTxRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RestQueryTxRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RestQueryTxRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Txhash) > 0 {
		i -= len(m.Txhash)
		copy(dAtA[i:], m.Txhash)
		i = encodeVarintRestQuery(dAtA, i, uint64(len(m.Txhash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RestTxResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RestTxResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RestTxResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Code != 0 {
		i = encodeVarintRestQuery(dAtA, i, uint64(m.Code))
		i--
		dAtA[i] = 0x10
	}
	if m.TxResponse != nil {
		{
			size, err := m.TxResponse.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRestQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RestQueryAppFeeGrantRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RestQueryAppFeeGrantRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RestQueryAppFeeGrantRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MisesUid) > 0 {
		i -= len(m.MisesUid)
		copy(dAtA[i:], m.MisesUid)
		i = encodeVarintRestQuery(dAtA, i, uint64(len(m.MisesUid)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.MisesAppid) > 0 {
		i -= len(m.MisesAppid)
		copy(dAtA[i:], m.MisesAppid)
		i = encodeVarintRestQuery(dAtA, i, uint64(len(m.MisesAppid)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AppFeeGrant) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AppFeeGrant) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AppFeeGrant) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Expiration != nil {
		n8, err8 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.Expiration, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.Expiration):])
		if err8 != nil {
			return 0, err8
		}
		i -= n8
		i = encodeVarintRestQuery(dAtA, i, uint64(n8))
		i--
		dAtA[i] = 0x1a
	}
	n9, err9 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.Period, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.Period):])
	if err9 != nil {
		return 0, err9
	}
	i -= n9
	i = encodeVarintRestQuery(dAtA, i, uint64(n9))
	i--
	dAtA[i] = 0x12
	if m.SpendLimit != nil {
		{
			size, err := m.SpendLimit.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRestQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RestQueryAppFeeGrantResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RestQueryAppFeeGrantResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RestQueryAppFeeGrantResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Grant != nil {
		{
			size, err := m.Grant.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRestQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintRestQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovRestQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *RestQueryDidRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MisesId)
	if l > 0 {
		n += 1 + l + sovRestQuery(uint64(l))
	}
	return n
}

func (m *RestQueryDidResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DidRegistry != nil {
		l = m.DidRegistry.Size()
		n += 1 + l + sovRestQuery(uint64(l))
	}
	return n
}

func (m *RestQueryUserRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MisesUid)
	if l > 0 {
		n += 1 + l + sovRestQuery(uint64(l))
	}
	return n
}

func (m *RestQueryUserResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PubInfo != nil {
		l = m.PubInfo.Size()
		n += 1 + l + sovRestQuery(uint64(l))
	}
	if m.PriInfo != nil {
		l = m.PriInfo.Size()
		n += 1 + l + sovRestQuery(uint64(l))
	}
	if m.Version != 0 {
		n += 1 + sovRestQuery(uint64(m.Version))
	}
	return n
}

func (m *RestQueryUserRelationRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MisesUid)
	if l > 0 {
		n += 1 + l + sovRestQuery(uint64(l))
	}
	l = len(m.Filter)
	if l > 0 {
		n += 1 + l + sovRestQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovRestQuery(uint64(l))
	}
	return n
}

func (m *MisesID) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MisesId)
	if l > 0 {
		n += 1 + l + sovRestQuery(uint64(l))
	}
	l = len(m.RelType)
	if l > 0 {
		n += 1 + l + sovRestQuery(uint64(l))
	}
	return n
}

func (m *RestQueryUserRelationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.MisesList) > 0 {
		for _, e := range m.MisesList {
			l = e.Size()
			n += 1 + l + sovRestQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovRestQuery(uint64(l))
	}
	return n
}

func (m *RestQueryAppRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MisesAppid)
	if l > 0 {
		n += 1 + l + sovRestQuery(uint64(l))
	}
	return n
}

func (m *RestQueryAppResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PubInfo != nil {
		l = m.PubInfo.Size()
		n += 1 + l + sovRestQuery(uint64(l))
	}
	if m.Version != 0 {
		n += 1 + sovRestQuery(uint64(m.Version))
	}
	return n
}

func (m *RestQueryTxRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Txhash)
	if l > 0 {
		n += 1 + l + sovRestQuery(uint64(l))
	}
	return n
}

func (m *RestTxResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TxResponse != nil {
		l = m.TxResponse.Size()
		n += 1 + l + sovRestQuery(uint64(l))
	}
	if m.Code != 0 {
		n += 1 + sovRestQuery(uint64(m.Code))
	}
	return n
}

func (m *RestQueryAppFeeGrantRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MisesAppid)
	if l > 0 {
		n += 1 + l + sovRestQuery(uint64(l))
	}
	l = len(m.MisesUid)
	if l > 0 {
		n += 1 + l + sovRestQuery(uint64(l))
	}
	return n
}

func (m *AppFeeGrant) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SpendLimit != nil {
		l = m.SpendLimit.Size()
		n += 1 + l + sovRestQuery(uint64(l))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.Period)
	n += 1 + l + sovRestQuery(uint64(l))
	if m.Expiration != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.Expiration)
		n += 1 + l + sovRestQuery(uint64(l))
	}
	return n
}

func (m *RestQueryAppFeeGrantResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Grant != nil {
		l = m.Grant.Size()
		n += 1 + l + sovRestQuery(uint64(l))
	}
	return n
}

func sovRestQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozRestQuery(x uint64) (n int) {
	return sovRestQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RestQueryDidRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRestQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RestQueryDidRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RestQueryDidRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MisesId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRestQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRestQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRestQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MisesId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRestQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRestQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RestQueryDidResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRestQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RestQueryDidResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RestQueryDidResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DidRegistry", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRestQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRestQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRestQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DidRegistry == nil {
				m.DidRegistry = &DidRegistry{}
			}
			if err := m.DidRegistry.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRestQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRestQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RestQueryUserRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRestQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RestQueryUserRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RestQueryUserRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MisesUid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRestQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRestQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRestQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MisesUid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRestQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRestQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RestQueryUserResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRestQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RestQueryUserResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RestQueryUserResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRestQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRestQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRestQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PubInfo == nil {
				m.PubInfo = &PublicUserInfo{}
			}
			if err := m.PubInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PriInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRestQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRestQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRestQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PriInfo == nil {
				m.PriInfo = &PrivateUserInfo{}
			}
			if err := m.PriInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			m.Version = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRestQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Version |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipRestQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRestQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RestQueryUserRelationRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRestQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RestQueryUserRelationRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RestQueryUserRelationRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MisesUid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRestQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRestQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRestQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MisesUid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Filter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRestQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRestQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRestQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Filter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRestQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRestQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRestQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRestQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRestQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MisesID) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRestQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MisesID: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MisesID: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MisesId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRestQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRestQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRestQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MisesId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RelType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRestQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRestQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRestQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RelType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRestQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRestQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RestQueryUserRelationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRestQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RestQueryUserRelationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RestQueryUserRelationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MisesList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRestQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRestQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRestQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MisesList = append(m.MisesList, &MisesID{})
			if err := m.MisesList[len(m.MisesList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRestQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRestQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRestQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRestQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRestQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RestQueryAppRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRestQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RestQueryAppRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RestQueryAppRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MisesAppid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRestQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRestQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRestQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MisesAppid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRestQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRestQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RestQueryAppResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRestQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RestQueryAppResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RestQueryAppResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRestQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRestQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRestQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PubInfo == nil {
				m.PubInfo = &PublicAppInfo{}
			}
			if err := m.PubInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			m.Version = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRestQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Version |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipRestQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRestQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RestQueryTxRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRestQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RestQueryTxRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RestQueryTxRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Txhash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRestQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRestQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRestQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Txhash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRestQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRestQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RestTxResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRestQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RestTxResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RestTxResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxResponse", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRestQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRestQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRestQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TxResponse == nil {
				m.TxResponse = &types.TxResponse{}
			}
			if err := m.TxResponse.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRestQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipRestQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRestQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RestQueryAppFeeGrantRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRestQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RestQueryAppFeeGrantRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RestQueryAppFeeGrantRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MisesAppid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRestQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRestQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRestQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MisesAppid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MisesUid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRestQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRestQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRestQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MisesUid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRestQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRestQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AppFeeGrant) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRestQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AppFeeGrant: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AppFeeGrant: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SpendLimit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRestQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRestQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRestQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SpendLimit == nil {
				m.SpendLimit = &types.Coin{}
			}
			if err := m.SpendLimit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Period", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRestQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRestQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRestQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.Period, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Expiration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRestQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRestQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRestQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Expiration == nil {
				m.Expiration = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.Expiration, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRestQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRestQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RestQueryAppFeeGrantResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRestQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RestQueryAppFeeGrantResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RestQueryAppFeeGrantResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Grant", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRestQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRestQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRestQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Grant == nil {
				m.Grant = &AppFeeGrant{}
			}
			if err := m.Grant.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRestQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRestQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRestQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRestQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRestQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRestQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthRestQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupRestQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthRestQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthRestQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRestQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupRestQuery = fmt.Errorf("proto: unexpected end of group")
)
